# Methodology

#### Ryan Angi

This app turns Vegas odds (American odds) into implied probabilities and compares them to the frequency of RV predictions of a death, taking the throne, or dying first for those who entered the pool. I was unable to find reliable American odds for last to die so that is not included in this analysis. 

Notes:  

  + In cases where there were no betting odds for a character (i.e. Dragons/Direwolves) I treated the Vegas odds as +100 (or 50% probability - even).  
  + In the case of no one taking the throne or no one on the list taking the throne I had to treat that as 0% probability because the odds were already distributed between the other chracters and it would have created unnatural estimates if I had imputed a higher value. For those who selected these values for taking the throne, their predicted average value is underestimated.  

## Leaderboard  

The leaderboard is sorted by the expected total points for each submission. This is a combination of points for "taking the throne" predictions, "death pool" predictions, and "first death" predictions. 

$$Expected\ Thrones\ Points = 7 \times Vegas\ Implied\ Probability\ To\ Take\ The\ Throne\ $$

----

For $k$ total characters. 

$$Expected\ Death\ Pool\ Points = \sum_{n=1}^{k} \cases{
     \Big( \big(4 \times \frac{1}{6-current\ episode} + 1 \times \big(1-\frac{1}{6-current\ episode}\big)\big) \times Vegas\ Implied\ Probability\ To\ Die_{n} \Big) - 1 \times \Big((1 - Vegas\ Implied\ Probability\ To\ Die_{n})\Big), & if Predicted Episode of Death > current episode  \cr
     \Big(1 \times Vegas\ Implied\ Probability\ To\ Die_{n} \big) - 1 \times \big((1 - Vegas\ Implied\ Probability\ To\ Die_{n}) \Big),              & if Predicted Episode of Death <= current episode  \cr
     0,  & otherwise (predicted survival) 
}
$$


----

$$Expected\ First\ Death\ Points = 4 \times Vegas\ Implied\ Probability\ To\ Die\ First$$

----

$$ Total\ Expected\ Points = Expected\ Future\ Thrones\ Points + Expected\ Future\ Death\ Pool\ Points + Expected\ Future\ First\ Death\ Points + Actual\ Points $$

Actual values will be combined with expected future values to update the leaderboard throughout the season.  
Again, last death is not included in this analysis.

